In [28]:
############################################ Import Python Libraries Required ############################################ 
import numpy as np
import pandas as pd
import scipy

import matplotlib.pyplot as plt
from matplotlib.ticker import FormatStrFormatter
import matplotlib.colors

import datetime
import os 
from os import path
import seaborn as sns
from scipy import signal

import warnings
warnings.filterwarnings('ignore')

import pickle

import statistics
import math 
pd.set_option('display.max_columns', 20)
pd.set_option('display.max_rows', 20)
# %config InlineBackend.figure_format = 'retina'
from PIL import Image
with open('Data_Files/ensemblemean324.pkl', 'rb') as f:
    ensemble_mean = pickle.load(f)


with open('Data_Files/ensembleub324.pkl', 'rb') as f:
    ensemble_ub = pickle.load(f)

with open('Data_Files/ensemblelb324.pkl', 'rb') as f:
    ensemble_lb = pickle.load(f)

with open('Data_Files/ensemblesem324.pkl', 'rb') as f:
    ensemble_sem = pickle.load(f)

In [29]:
start ="01-11-2021"
end  = "30-06-2022"

start = datetime.datetime.strptime(start, "%d-%m-%Y")
end = datetime.datetime.strptime(end, "%d-%m-%Y")
date_g= [start + datetime.timedelta(days=x) for x in range(0, (end-start).days+2)]

In [30]:
from datetime import datetime

In [31]:
date =[]
for i in range(len(date_g)):

    date.append(date_g[i].strftime('%m/%d/%Y'))

In [39]:
value = ensemble_mean[488:]
fct_ub = ensemble_ub[488:]
fct_lb = ensemble_lb[488:]
fct_std = ensemble_sem[488:]


df =pd.DataFrame()
df['date'] = date
df['value'] = value
df['ub'] = fct_ub
df['lb'] = fct_lb
df['std'] = fct_std

df

           date        value           ub           lb         std
0    11/01/2021  1025.685185  1123.020206   928.350164   97.335021
1    11/02/2021  1080.074074  1184.413611   975.734538  104.339537
2    11/03/2021  1141.796296  1254.046933  1029.545659  112.250637
3    11/04/2021  1211.685185  1332.880860  1090.489510  121.195675
4    11/05/2021  1290.759259  1422.073561  1159.444957  131.314302
..          ...          ...          ...          ...         ...
238  06/27/2022  1131.098765  1259.320029  1002.877501  128.221264
239  06/28/2022  1106.000000  1231.099970   980.900030  125.099970
240  06/29/2022  1081.697531  1203.776799   959.618263  122.079268
241  06/30/2022  1058.240741  1177.392429   939.089053  119.151688
242  07/01/2022  1035.450617  1151.766812   919.134422  116.316195

[243 rows x 5 columns]

In [ ]:
df.to_csv('ISI.csv')